# Site settings
title: Melanie Richards | Seattle web design and development
email: hello@melanie-richards.com
url: "http://melanie-richards.com"
images: /assets/images/content

# Blog settings
paginate: 16
paginate_path: "/blog/page:num/"
permalink: /blog/:title/

# Gems
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
source: _source
sass:
  sass_dir: assets/_sass
  style: compressed